config/routes.rb
Rails.application.routes.draw do
  get 'index/index'

  resources :users do
    resources :tweets, only: [:index]
  end
  
  resources :tweets, only: [:show, :new, :create, :destroy]

  post 'follow/:id' => 'follows#follow', as: :follow
  delete 'follow/:id' => 'follows#unfollow', as: :unfollow
  

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

root 'index#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  
  validates :post, presence: true, length: { minimum: 5, maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets, dependent: :destroy

  has_many :followee_relationships, class_name: "UserRelation",
                                       foreign_key: "followee_id",
                                       dependent: :destroy
  has_many :followees, through: :followee_relationships, source: :follower
  
  has_many :follower_relationships, class_name: "UserRelation",
                                       foreign_key: "follower_id",
                                       dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :followee
  
  


  has_secure_password
  validates :password, length: { minimum: 6 }

  
  validates :name, presence: true,
    length: { minimim: 3, maximum: 20}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
  validates :email, presence: true,
    format: { with: VALID_EMAIL_REGEX },     
    uniqueness: { case_sensitive: false }
    
  def following?(user_id)
    followees.pluck(:id).include? user_id
  end

  def following?(user_id)
    followees.pluck(:id).include? user_id
  end

end

app/models/user_relation.rb
class UserRelation < ActiveRecord::Base
  belongs_to :follower, class_name: User
  belongs_to :followee, class_name: User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected
  
  def current_user
    @user = logged_in? ? User.find(session[:user]) : nil
  end
  
  def get_user_by_id(user_id = nil)
    !!user_id ? User.find(user_id) : User.find(params[:id])
  end
  
  def logged_in?
    !!session[:user]
  end
  
  def redirect_if_logged_in!
    redirect_to login_path unless logged_in?
  end
  
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :redirect_if_logged_in!
  before_action :current_user
  
  def follow
    target_user = get_user_by_id(params[:id])
    if !!target_user
      @user.followers << target_user
      flash[:success] = "followed user"
      redirect_to target_user
    else
      flash[:danger] = "failed following user"
      redirect_to '/index/index'
    end
  end
  
  def unfollow
    target_user = get_user_by_id(params[:id])
    if !!target_user
      @user.followers.delete target_user
      flash[:success] = "unfollowed user"
      redirect_to target_user
    else
      flash[:danger] = "failed unfollowing user"
      redirect_to '/index/index'
    end
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
    @user = current_user
    @tweets = Tweet.order("created_at desc")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  # login画面まで
  def new
    @user = User.new 
  end
  
  # login logic
  def create
    user = User.where(email: params[:user][:email]).first
    # password check
    
    user = user.authenticate(params[:user][:password]) if !!user
    # !!は nil, false等であれは否定の否定を行うことで存在:true 非存在:false
    if !!user
      session[:user] = user.id
      redirect_to '/index/index'
    else
      flash[:danger] = '認証に失敗しました'
      render action: :new
    end
  end
  
  # logout logic
  def destroy
    reset_session
    render action: :new
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :redirect_if_logged_in!
  before_action :current_user, only: [:new, :create, :destroy]   
  
  def index
    @tweets = Tweet.where(user_id: params[:user_id])  
  end
  
  def new
    @tweet = @user.tweets.new
  end
  
  def create
    @tweet = @user.tweets.create(tweet_params)
    if @tweet.save
      flash[:success] = 'you''ve posted new tweet'
      redirect_to '/index/index'
    else
      flash[:danger] = 'failed to create tweet'
      render 'new'
    end
  end
  
  def destroy
    tweet = Tweet.where(id: params[:id]).first
    if(!!tweet && tweet.user == @user)
      tweet.destroy
      flash[:success] = 'deleted tweet'
    else
      flash[:danger] = 'failed deletion tweet'
    end
    
    redirect_to '/index/index'
  end
  

  
  private
  
  def tweet_params
    params.require(:tweet).permit([:post])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_logged_in!, only: [:show, :destroy, :edit, :update]
  before_action :get_user, only: [:show, :destroy, :edit, :update]
  
  def index
    redirect_to login_path
  end
  
  def show
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_param) 
    if @user.save
      flash[:success] = 'user created successfully'
      redirect_to users_path
    else
      flash[:danger] = 'invalid input'
      render 'new'
    end
  end
  
  def destroy
    @user.destroy
    redirect_to users_path
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_param)
      redirect_to users_path
    else
      flash[:danger] = '更新に失敗しました'
      render 'edit'
    end
  end
  
  
  private
  
  def user_param
    params.require(:user).permit([:name, :email, :password, :password_confirmation])
  end
  
  def get_user
    @user = get_user_by_id(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/index.html.erb
<h1>Index#index</h1>
<p>Find me in app/views/index/index.html.erb</p>
<% if !!session[:user] %>
    <p>
      <%= link_to 'new tweet', new_tweet_path %>
    </p>
<% else %>
    <p><%= link_to 'login', login_path %></p>
<% end %>
<div>
  <ul>
  <% @tweets.each do |tweet| %>
      <li>
        <%= tweet.post %>
        <% if !!session[:user] %>
        : by <%= link_to tweet.user.name, user_path(tweet.user) %>
        : at <%= tweet.created_at %> :
            <% if session[:user] == tweet.user.id %>
              <%= link_to 'delete', tweet_path(tweet), method: :delete %>
            <% end %>
        <% end %>
      </li>
  <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TweetClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:danger] %>
  <%= flash[:danger] %>
<% end %>

<% if flash[:success] %>
  <%= flash[:success] %>
<% end %>

<% if !!session[:user] %>
  ログインしています: <% session[:user] %>
  <%= link_to 'ログアウト', logout_path %>
<% else %>
  ログインしていません
<% end %>

<%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<%= @tweets %>
<ul>
<% @tweets.each do |tweet| %>
  <li><%= tweet.post %> - by <%= tweet.user.name%></li>  
<% end %>
  
</ul>

app/views/tweets/new.html.erb
<div>
  create new tweet
</div>
<div>
  <%= form_for @tweet do |f| %>
  <ul>
    <li>
      tweet: <%= f.text_field :post %>
    </li>
    <li>
      <%= f.submit 'create tweet' %>
    </li>
  </ul>
  <% end %>
</div>

app/views/users/_form.html.erb
  <% if !!flash[:danger] %>
    <%= flash[:danger] %>
  <% end %>
  <%= form_for @user do |f| %>
  <ul>
    <li>name:<%= f.text_field :name %></li>
    <li>email:<%= f.text_field :email %></li>
    <li>password:<%= f.password_field :password %></li>
    <li>password(confirm):<%= f.password_field :password_confirmation %></li>
    <li><%= f.submit submit %></li>
  </ul>
  <% end %> 

app/views/users/_user.html.erb
<li>#<%= user.id%> : <%= user.name %> : <%= user.email %></li>

app/views/users/edit.html.erb
<html>
  <h1>edit user</h1>
  <div>
    <%= render partial: 'form', locals: { submit: '更新'} %>
  </div>
</html>

app/views/users/index.html.erb
<html>
  <h1>users index</h1>
  <h2><%= @users %></h2>
  <div>
    <% @users.each do |user| %>
      ID: <%= user.id %>, name: <%= user.name %>, email: <%= user.email %>
      <%= link_to 'show', user %>
      <%= link_to 'edit', edit_user_path(user) %>
      <%= link_to 'delete', user, method: :delete %>
      <br>
    <% end %>
  </div>
</html>

app/views/users/new.html.erb
<html>
  <h1>register</h1>
  <%= render partial: 'form', locals: { submit: 'register'} %>
</html>

app/views/users/show.html.erb
<html>
  <h1>show user</h1>
  <ul>
    <li><%= @user.id %></li>
    <li><%= @user.name %></li>
    <li><%= @user.email %></li>
    <li>
      <% if @user.following? session[:user] %>
        now you are following this user
        <%= link_to 'unfollow', follow_path(@user), method: :delete %>
      <% elsif @user.id != session[:user] %>
        now you are not following this user
        <%= link_to 'follow', follow_path(@user), method: :post %>
      <% else %>
        it's you
      <% end %>
    </li>
  </ul>
  <div>
    <h2>this user follows</h2>
    <ul>
      <%= render @user.followers %>
    </ul>  
  </div>
  
  <div>
    <h2>this user is followed by</h2>
    <ul>
      <%= render @user.followees %>
    </ul>  
  </div>
  
</html>